# Generated by Django 4.2.1 on 2023-05-08 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(choices=[('Masculino', 'masculino'), ('Femenina', 'femenina')], max_length=10)),
                ('height', models.CharField(max_length=6)),
                ('weight', models.CharField(max_length=6)),
                ('exersice', models.CharField(choices=[('Si', 'si'), ('No', 'no')], max_length=10)),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
